# docker-compose.override.yml pour le développement
version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      target: builder
    volumes:
      - ./user-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - ENABLE_FILE_SERVICE=false
      - MOCK_FILE_SERVICE=true
      - ENABLE_KAFKA=false
    command: npm run dev

  user-db:
    environment:
      - POSTGRES_DB=user_db_dev
    volumes:
      - ./user-service/scripts/init-dev-db.sql:/docker-entrypoint-initdb.d/99-init-dev.sql