# docker-compose.prod.yml (pour la production)
version: '3.8'

services:
  auth-service:
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    command: npm start
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  auth-db:
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - auth-db-prod-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3

  auth-redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - auth-redis-prod-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

volumes:
  auth-db-prod-data:
    external: true
  auth-redis-prod-data:
    external: true